---
version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.0-apache-jessie-node-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-{{ checksum "composer.lock" }}
      - run: composer install --no-interaction
      - save_cache:
          key: v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - run: vendor/bin/phpunit --log-junit /tmp/test-results/phpunit/junit.xml
      - store_test_results:
          path: /tmp/test-results
  deploy:
    docker:
      - image: circleci/php:7.0-apache-jessie-node-browsers
    steps:
      - checkout
      - add_ssh_keys
      - run: ssh-keyscan farnsworth.ch >> ~/.ssh/known_hosts
      - deploy: ssh farnswor@farnsworth.ch 'cd /home/farnswor/public_html/trnsprt.ch && git pull --rebase --stat && php -d allow_url_fopen=on -d disable_functions=exec composer.phar install --no-dev --no-interaction && chmod -R u+rwX,go+rX,go-w .'

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
